apiVersion: v1
data:
  APPD_DIR: /appdynamics
  APPD_ES_HOST: "<events-service-url>"
  APPD_ES_PORT: "9080"
  APPD_ES_SSL: "false"
  APPD_EVENT_ACCOUNT_NAME: "<your-global-account-name>"
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "<controller-access-key>"
  APPDYNAMICS_AGENT_ACCOUNT_NAME: <controller-customer-name>
  APPDYNAMICS_AGENT_APPLICATION_NAME: "<your-application-name>"
  APPDYNAMICS_CONTROLLER_HOST_NAME: "<controller-host>"
  APPDYNAMICS_CONTROLLER_PORT: "8090"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "False"
  APPDYNAMICS_NETVIZ_AGENT_PORT: "3892"
  ROOKOUT_LABELS: "env:<rookout-label>"
  ROOKOUT_LOG_TO_STDERR: "True"
  ROOKOUT_DEBUG: "1"
  ROOKOUT_COMMIT: "True"
  ROOKOUT_TOKEN: "<rookout-token>"
  RETRY: 10s
  TIMEOUT: 300s
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: env-map
