# harness.io/skip-file-for-deploy
apiVersion: v1
data:
  APPD_DIR: /appdynamics
  APPD_ES_HOST: "<events-service-url>"
  APPD_ES_PORT: "9080"
  APPD_ES_SSL: "false"
  APPD_EVENT_ACCOUNT_NAME: "customer1_5d98385e-059a-4a87-ae81-4aa347ecf709"
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: ""
  APPDYNAMICS_AGENT_ACCOUNT_NAME: ""
  APPDYNAMICS_AGENT_APPLICATION_NAME: "AD-Capital-GCP"
  APPDYNAMICS_CONTROLLER_HOST_NAME: "geth-ctrl-ckhlznyk.appd-sales.com"
  APPDYNAMICS_CONTROLLER_PORT: "8090"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "False"
  APPDYNAMICS_NETVIZ_AGENT_PORT: "3892"
  ROOKOUT_LABELS: "env:kevin-johnson-se-days"
  ROOKOUT_LOG_TO_STDERR: "True"
  ROOKOUT_DEBUG: "1"
  ROOKOUT_COMMIT: "True"
  ROOKOUT_TOKEN: "9a15b4957bc9b8d0d4d1babf46256a0d52e0bc21321e6f6610e2e7ce5c1444df"
  RETRY: 10s
  TIMEOUT: 300s
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: env-map
