# harness.io/skip-file-for-deploy
apiVersion: v1
data:
  APPD_DIR: /appdynamics
  APPD_ES_HOST: "https://analytics.api.appdynamics.com"
  APPD_ES_PORT: "9080"
  APPD_ES_SSL: "false"
  APPD_EVENT_ACCOUNT_NAME: "customer1_b8502d8b-1abc-472c-b825-f3ff8e61b075"
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: ""
  APPDYNAMICS_AGENT_ACCOUNT_NAME: ""
  APPDYNAMICS_AGENT_APPLICATION_NAME: "AD-Capital-SE-Days"
  APPDYNAMICS_CONTROLLER_HOST_NAME: "apacsedays2020-2033nos-lu8bu4rw.appd-sales.com"
  APPDYNAMICS_CONTROLLER_PORT: "8090"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "False"
  APPDYNAMICS_NETVIZ_AGENT_PORT: "3892"
  ROOKOUT_LABELS: "env:rishikesh-r-se-days"
  ROOKOUT_LOG_TO_STDERR: "True"
  ROOKOUT_DEBUG: "1"
  ROOKOUT_COMMIT: "True"
  ROOKOUT_TOKEN: "93e55836f03a56d1251115c85e1077eef418509dda06c3ef17c04acebe998fa1"
  RETRY: 10s
  TIMEOUT: 300s
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: env-map
